export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_UNSEEN_IMAGES = 'USER_UNSEEN_IMAGES';
export const USER_UNSEEN_IMAGES_SUCCESS = 'USER_UNSEEN_IMAGES_SUCCESS';
export const USER_UNSEEN_IMAGES_FAIL = 'USER_UNSEEN_IMAGES_FAIL';