export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_UPDATE = 'USER_UPDATE';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_UNSEEN_IMAGES = 'USER_UNSEEN_IMAGES';
export const USER_UNSEEN_IMAGES_SUCCESS = 'USER_UNSEEN_IMAGES_SUCCESS';
export const USER_UNSEEN_IMAGES_FAIL = 'USER_UNSEEN_IMAGES_FAIL';
