export const FETCH_UNSEEN_IMAGES = 'FETCH_UNSEEN_IMAGES';
export const FETCH_UNSEEN_IMAGES_SUCCESS = 'FETCH_UNSEEN_IMAGES_SUCCESS';
export const FETCH_UNSEEN_IMAGES_FAIL = 'FETCH_UNSEEN_IMAGES_FAIL';


export const SET_IMAGE_SEEN = 'SET_IMAGE_SEEN';
export const SET_IMAGE_SEEN_SUCCESS = 'SET_IMAGE_SEEN_SUCCESS';
export const SET_IMAGE_SEEN_FAIL = 'SET_IMAGE_SEEN_FAIL';
